spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 944954562684-cqcrkqgpkgpdi75i3dv0ldh2su5m2kit.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
          naver:
            client-id: 8ynxtdO68Bv2M9WqXNWG
            client-secret: sEGiC14Xi7
            redirect-uri: "http://localhost:8080/login/oauth2/code/naver"
            authorization-grant-type: authorization_code
            scope:
              - email
              - name
              - profile_image
            client-name: Naver
          kakao:
            authorization-grant-type: authorization_code
            client-id: 2d581658ea1a5af627d21fc898f50a4a
            client-secret: T5KBmXVxz7UpIjMid9TYoJKgMWEokcDh
            redirect-uri: "http://localhost:8080/login/oauth2/code/kakao"
            scope:
              - account_email
              - profile_nickname
              - profile_image
            client-authentication-method: POST
            client-name: Kakao
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id