spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/sunin
  security:
    user:
      name: ssafy
      password: ssafy
  datasource:
    url: jdbc:mysql://localhost:3306/sunin?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: ssafy
    password: ssafy
  jpa:
    hibernate:
      ddl-auto: create # 유의해주세요!!
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
#logging:
#  level:
#    org:
#      springframework:
#        data:
#          mongodb:
#            core:
#              MonogoTemplate: debug
##        web: debug
#    hibernate:
#      SQL: debug
#      type: trace